global:
  scrape_interval: 5s

scrape_configs:

  # Monitor Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  # Node Exporter
  - job_name: "node_exporter"
    static_configs:
      - targets: ["node_exporter:9100"]

  # PostgreSQL Exporter
  - job_name: "postgres_exporter"
    static_configs:
      - targets: ["postgres_exporter:9187"]

  # Custom Exporter
  - job_name: "custom_exporter"
    static_configs:
      - targets: ["custom_exporter:8000"]
